name: CopyTo

on:
  push:
    branches:
    - master

jobs:
  pushGitJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir -p ~/.ssh
    - run: echo $netrc > ~/.netrc
      env:
        netrc: ${{ secrets.netrc }}
    - run: git clone https://github.com/pCYSl5EDgo/UniNativeLinq-EditorExtension-Test.git
    - name: Copy
      run: |
        cp -f -r Editor/CodeGenerator "UniNativeLinq-EditorExtension-Test/Assets/UniNativeLinq-EditorExtension/Editor"
        cp -f -r Editor/ScriptableObject "UniNativeLinq-EditorExtension-Test/Assets/UniNativeLinq-EditorExtension/Editor"
        cp -f -r Editor/View "UniNativeLinq-EditorExtension-Test/Assets/UniNativeLinq-EditorExtension/Editor"
        cp -f -r Editor/Utility "UniNativeLinq-EditorExtension-Test/Assets/UniNativeLinq-EditorExtension/Editor"
        cp -f -r Editor/DLLs/UniNativeLinq.bytes "UniNativeLinq-EditorExtension-Test/Assets/UniNativeLinq-EditorExtension/Editor/DLLs/UniNativeLinq.bytes"
    - run: |
        cd UniNativeLinq-EditorExtension-Test
        git config --global user.email "pcysl5edgo@yahoo.co.jp"
        git config --global user.name "pCYSl5EDgo"
        git commit -a -m "[update]DLL Update of $GITHUB_SHA"
        git push -v
